version: '3.5'

services:
  postgres:
    container_name: click-house
    image: yandex/clickhouse-server
    volumes:
       - ./statistics-db:/var/lib/clickhouse
    ports:
      - "9000:9000"
      - "8123:8123"
    networks:
      - ch-network
    restart: unless-stopped
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144

networks:
  ch-network:
    driver: bridge
