version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres:15.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    volumes:
       - ~/Files/Docker/Data/postgres:/var/lib/postgresql/data
       - ~/Files/Docker/Data/shared:/var/lib/postgresql/backups
    ports:
      - "5432:5432"
    networks:
      - postgres-network
    restart: unless-stopped

networks:
  postgres-network:
    driver: bridge
