version: '3.8'

services:
  mongo:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - ~/Files/Docker/Data/mongodb:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
    depends_on:
      - mongo